# 应用服务 WEB 访问端口
server:
  port: 10000

spring:
  application:
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
#  instance:
#    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        # 暴露所有的监控端点 # 如果一个服务需要被监控 那么就要讲自身的一些情况(一些信息接口)暴露出去
        include: '*'

