# 应用服务 WEB 访问端口
server:
  port: 10001
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

zuul:
  #prefix: /api
  #strip-prefix: true
  routes:
    service-server:
      path: /service/**
      url: http://localhost:10011
    api-server:
      path: /api/**
      url: http://localhost:10012
